language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
 - openjdk8
 - oraclejdk8
 - openjdk11
 - oraclejdk11
 - oraclejdk9
before_script:
   - sudo apt-get install ant-optional
addons:
  apt:
    packages:
      - ant ./apache/lib/ant.jar